name: Build ESP8266 Firmware

on:
  push:
    tags:
      - 'v*'  # Trigger on tag pushes like v1.0.3, v1.0.4, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install PlatformIO
        run: pip install platformio

      - name: Install ESP8266 Platform
        run: platformio platform install espressif8266@3.1.2

      - name: Check PlatformIO Version
        run: pio platform show espressif8266

      - name: Install Dependencies
        run: platformio pkg install

      - name: Clean Build
        run: pio run -t clean

      - name: Build Firmware
        run: platformio run

      - name: Upload Firmware as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ESP8266-LED-OTA.bin
          path: .pio/build/nodemcuv2/firmware.bin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Latest Firmware ${{ github.ref }}
          body: New firmware build from latest commit.
          files: .pio/build/nodemcuv2/firmware.bin
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
