name: Build ESP8266 Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install PlatformIO
        run: pip install platformio

      - name: Install Dependencies
        run: platformio lib install

      - name: Build Firmware
        run: platformio run

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 1.0.2
          files: .pio/build/nodemcuv2/firmware.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Firmware as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ESP8266-LED-OTA.bin
          path: .pio/build/nodemcuv2/firmware.bin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 1.0.2  # You can use a specific tag like 1.0.1, or 'latest'
          name: Latest Firmware 1.0.2  # This is where you specify the release name
          body: New firmware build from latest commit.
          files: .pio/build/nodemcuv2/firmware.bin  # Path to the firmware .bin file
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Authentication with GitHub token

